const explicitSettingLabels = {
  'scum.ServerName': '服务器名称',
  'scum.ServerDescription': '服务器描述',
  'scum.ServerPassword': '服务器密码',
  'scum.ServerBannerUrl': '服务器横幅地址',
  'scum.ServerPlaystyle': '服务器玩法',
  'scum.WelcomeMessage': '欢迎消息',
  'scum.MessageOfTheDay': '每日消息',
  'scum.MessageOfTheDayCooldown': '每日消息冷却时间',
  'scum.MinServerTickRate': '最小服务器帧率',
  'scum.MaxServerTickRate': '最大服务器帧率',
  'scum.MaxPing': '最大延迟',
  'scum.LogoutTimer': '登出等待时间',
  'scum.LogoutTimerWhileCaptured': '被控制时登出等待时间',
  'scum.LogoutTimerInBunker': '地堡内登出等待时间',
  'scum.AllowFirstPerson': '允许第一人称',
  'scum.AllowThirdPerson': '允许第三人称',
  'scum.AllowCrosshair': '允许准星',
  'scum.AllowVoting': '允许投票',
  'scum.AllowMapScreen': '允许地图',
  'scum.AllowKillClaiming': '允许击杀认领',
  'scum.AllowComa': '允许昏迷',
  'scum.AllowMinesAndTraps': '允许地雷和陷阱',
  'scum.AllowSkillGainInSafeZones': '允许在安全区获得技能经验',
  'scum.AllowEvents': '允许事件',
  'scum.LimitGlobalChat': '限制全局聊天',
  'scum.AllowGlobalChat': '允许全局聊天',
  'scum.AllowLocalChat': '允许本地聊天',
  'scum.AllowSquadChat': '允许小队聊天',
  'scum.AllowAdminChat': '允许管理员聊天',
  'scum.RustyLocksLogging': '记录生锈锁日志',
  'scum.HideKillNotification': '隐藏击杀通知',
  'scum.DisableTimedGifts': '禁用限时礼包',
  'scum.UseMapBaseBuildingRestriction': '启用地图建家限制',
  'scum.DisableBaseBuilding': '禁用建家',
  'scum.VotingDuration': '投票持续时间',
  'scum.PlayerMinimalVotingInterest': '投票最小参与比例',
  'scum.PlayerPositiveVotePercentage': '投票通过比例',
  'scum.MasterServerEndpoints': '主服务器节点',
  'scum.MasterServerUpdateSendInterval': '主服务器状态上报间隔',
  'scum.PartialWipe': '部分清档',
  'scum.GoldWipe': '金币清档',
  'scum.FullWipe': '完全清档',
  'scum.ItemVirtualizationRelevancyUpdatePeriod': '物品虚拟化相关性刷新周期',
  'scum.ItemVirtualizationEventProcessingTimeBudget': '物品虚拟化事件处理时间预算',
  'scum.ItemVirtualizationVisitorDistanceTravelledForUpdate': '物品虚拟化访客刷新移动距离',
  'scum.ItemVirtualizationVisitorBounds': '物品虚拟化访客范围',
  'scum.VirtualizedItemBounds': '虚拟化物品范围',
  'scum.FameGainMultiplier': '声望获取倍率',
  'scum.FamePointPenaltyOnDeath': '死亡声望惩罚',
  'scum.FamePointPenaltyOnKilled': '被击杀声望惩罚',
  'scum.FamePointRewardOnKill': '击杀声望奖励',
  'scum.LogSuicides': '记录自杀日志',
  'scum.EnableSpawnOnGround': '允许地面出生',
  'scum.DeleteInactiveUsers': '删除不活跃玩家',
  'scum.DaysSinceLastLoginToBecomeInactive': '判定不活跃登录天数',
  'scum.DeleteBannedUsers': '删除被封禁玩家',
  'scum.MaximumTimeForChestsInForbiddenZones': '禁建区箱子最大保留时间',
  'scum.LogChestOwnership': '记录箱子归属日志',
  'scum.ServerSettingsVersion': '服务器配置版本',
  'scum.DisableExamineGhost': '禁用检查残影',
  'scum.MasterServerIsLocalTest': '主服务器本地测试模式',
  'scum.MaxPingCheckEnabled': '启用最大延迟检测',
  'scum.PlaySafeIdProtection': '启用 PlaySafe 身份保护',
  'scum.DeleteDuplicateChestsOnServerStartup': '开服时删除重复箱子',
  'scum.UseBuildingProximityRestrictions': '启用建筑邻近限制',
  'scum.MaxAllowedBirds': '最大鸟类数量',
  'scum.MaxAllowedCharacters': '最大角色数量',
  'scum.MaxAllowedPuppets': '最大丧尸数量',
  'scum.MaxAllowedAnimals': '最大动物数量',
  'scum.MaxAllowedNPCs': '最大非玩家角色数量',
  'scum.MaxAllowedZombies': '最大僵尸数',
  'scum.MaxAllowedExteriorZombies': '最大室外僵尸数',
  'scum.MaxAllowedInteriorZombies': '最大室内僵尸数',
  'scum.MaxAllowedWildZombies': '最大野外僵尸数',
  'scum.MaxAllowedDrones': '最大无人机数量',
  'scum.ExteriorZombieAmountModifier': '户外僵尸倍率',
  'scum.InteriorZombieAmountModifier': '室内僵尸倍率',
  'scum.WildZombieAmountModifier': '野外僵尸倍率',
  'scum.ExteriorZombieSpawnerCooldownTimer': '户外僵尸刷新冷却时间',
  'scum.InteriorZombieSpawnerCooldownTimer': '室内僵尸刷新冷却时间',
  'scum.ExteriorZombieSpawningCheckTime': '户外僵尸刷新检查间隔',
  'scum.InteriorZombieSpawningCheckTime': '室内僵尸刷新检查间隔',
  'scum.WildZombieSpawningCheckTime': '野外僵尸刷新检查间隔',
  'scum.ExteriorZombieSpawningProbability': '户外僵尸刷新概率',
  'scum.InteriorZombieSpawningProbability': '室内僵尸刷新概率',
  'scum.PuppetHealthMultiplier': '僵尸生命倍率',
  'scum.DropshipHealthMultiplier': '空投飞船生命倍率',
  'scum.SentryHealthMultiplier': '机甲生命倍率',
  'scum.ArmedNPCDifficultyLevel': '武装非玩家角色难度等级',
  'scum.StartTimeOfDay': '开局时间',
  'scum.TimeOfDaySpeed': '昼夜流速',
  'scum.NighttimeDarkness': '夜晚黑暗程度',
  'scum.SunriseTime': '日出时间',
  'scum.SunsetTime': '日落时间',
  'scum.ShouldDestroyEntitiesOutsideMapLimitsOnRestart': '重启时清理地图外实体',
  'scum.EnableLockedLootContainers': '启用上锁战利品容器',
  'scum.CustomMapEnabled': '启用自定义地图范围',
  'scum.CustomMapCenterXCoordinate': '自定义地图中心 X 坐标',
  'scum.CustomMapCenterYCoordinate': '自定义地图中心 Y 坐标',
  'scum.CustomMapWidth': '自定义地图宽度',
  'scum.CustomMapHeight': '自定义地图高度',
  'scum.CargoDropCooldownMinimum': '空投最小冷却时间',
  'scum.CargoDropCooldownMaximum': '空投最大冷却时间',
  'scum.CargoDropFallDelay': '空投下落延迟',
  'scum.CargoDropFallDuration': '空投下落时长',
  'scum.CargoDropSelfdestructTime': '空投自毁时间',
  'scum.MaxAllowedHunts': '最大狩猎任务数量',
  'scum.HuntFailureTime': '狩猎失败时间',
  'scum.HuntFailureDistance': '狩猎失败距离',
  'scum.AbandonedBunkerMaxSimultaneouslyActive': '废弃地堡同时激活上限',
  'scum.AbandonedBunkerActiveDurationHours': '废弃地堡激活持续小时数',
  'scum.AbandonedBunkerKeyCardActiveDurationHours': '废弃地堡钥匙卡持续小时数',
  'scum.SecretBunkerKeyCardActiveDurationHours': '秘密地堡钥匙卡持续小时数',
  'scum.PuppetRunningSpeedMultiplier': '僵尸奔跑速度倍率',
  'scum.PuppetLimpingEnabled': '启用僵尸瘸行',
  'scum.ArmedNPCHealthMultiplier': '武装非玩家角色生命倍率',
  'scum.ArmedNPCDamageMultiplier': '武装非玩家角色伤害倍率',
  'scum.ArmedNPCSpreadMultiplier': '武装非玩家角色扩散倍率',
  'scum.ArmedNPCRunningSpeedMultiplier': '武装非玩家角色跑步速度倍率',
  'scum.ArmedNPCLimpingEnabled': '启用武装非玩家角色瘸行',
  'scum.EnableFog': '启用雾效',
  'scum.AbandonedBunkerBCUTerminalCooldown': '废弃地堡BCU终端冷却时间',
  'scum.DisableLootPuppetSpawning': '禁用战利品僵尸刷新',
  'scum.EnableLootPuppetHorde': '启用战利品僵尸群',
  'scum.FishingHighActivityZoneRotationTime': '高活跃钓鱼区轮换时间',
  'scum.AllowSectorRespawn': '允许区域复活',
  'scum.AllowShelterRespawn': '允许庇护所复活',
  'scum.AllowSquadmateRespawn': '允许队友身边复活',
  'scum.RandomRespawnPrice': '随机复活价格',
  'scum.SectorRespawnPrice': '区域复活价格',
  'scum.ShelterRespawnPrice': '庇护所复活价格',
  'scum.SquadRespawnPrice': '队友身边复活价格',
  'scum.RandomRespawnInitialTime': '随机复活初始等待时间',
  'scum.SectorRespawnInitialTime': '区域复活初始等待时间',
  'scum.ShelterRespawnInitialTime': '庇护所复活初始等待时间',
  'scum.SquadRespawnInitialTime': '队友身边复活初始等待时间',
  'scum.RandomRespawnCooldown': '随机复活冷却时间',
  'scum.SectorRespawnCooldown': '区域复活冷却时间',
  'scum.ShelterRespawnCooldown': '庇护所复活冷却时间',
  'scum.SquadRespawnCooldown': '队友身边复活冷却时间',
  'scum.RandomCooldownResetMultiplier': '随机复活冷却重置倍率',
  'scum.SectorCooldownResetMultiplier': '区域复活冷却重置倍率',
  'scum.ShelterCooldownResetMultiplier': '庇护所复活冷却重置倍率',
  'scum.SquadCooldownResetMultiplier': '队友身边复活冷却重置倍率',
  'scum.RandomPricePerSquadmateModifier': '随机复活每名队友价格修正',
  'scum.SectorPricePerSquadmateModifier': '区域复活每名队友价格修正',
  'scum.ShelterPricePerSquadmateModifier': '庇护所复活每名队友价格修正',
  'scum.CommitSuicideInitialTime': '自杀初始等待时间',
  'scum.CommitSuicideCooldown': '自杀冷却时间',
  'scum.CommitSuicideCooldownResetMultiplier': '自杀冷却重置倍率',
  'scum.MaximumBaseProximityWhenSpawning': '复活时允许靠近基地最大距离',
  'scum.PermadeathThreshold': '永久死亡阈值',
  'scum.ShelterRespawnPriceOutsideFlagArea': '旗帜区外庇护所复活价格',
  'scum.FuelDrainFromEngineMultiplier': '引擎燃油消耗倍率',
  'scum.BatteryDrainFromEngineMultiplier': '引擎电池消耗倍率',
  'scum.BatteryDrainFromDevicesMultiplier': '设备电池消耗倍率',
  'scum.BatteryDrainFromInactivityMultiplier': '闲置电池消耗倍率',
  'scum.BatteryChargeWithAlternatorMultiplier': '发电机充电倍率',
  'scum.BatteryChargeWithDynamoMultiplier': '车轮发电充电倍率',
  'scum.MaximumTimeOfVehicleInactivity': '载具闲置最大时间',
  'scum.MaximumTimeForVehiclesInForbiddenZones': '禁建区载具最大保留时间',
  'scum.LogVehicleDestroyed': '记录载具摧毁日志',
  'scum.HumanToHumanDamageMultiplier': '玩家对玩家伤害倍率',
  'scum.HumanToHumanArmedMeleeDamageMultiplier': '武器近战对玩家伤害倍率',
  'scum.HumanToHumanUnarmedMeleeDamageMultiplier': '徒手对玩家伤害倍率',
  'scum.HumanToHumanThrowingDamageMultiplier': '投掷物对玩家伤害倍率',
  'scum.SentryDamageMultiplier': '机甲伤害倍率',
  'scum.ZombieDamageMultiplier': '僵尸伤害倍率',
  'scum.ItemDecayDamageMultiplier': '物品腐坏倍率',
  'scum.FoodDecayDamageMultiplier': '食物腐坏倍率',
  'scum.LockProtectionDamageMultiplier': '锁具防护伤害倍率',
  'scum.SentryRailgunDamageMultiplier': '机甲轨道炮伤害倍率',
  'scum.SentryGrenadeDamageMultiplier': '机甲榴弹伤害倍率',
  'scum.BaseBuildingAttackerSentryDamageMultiplier': '攻基地机甲伤害倍率',
  'scum.BaseBuildingAttackerSentryRailgunDamageMultiplier': '攻基地机甲轨道炮伤害倍率',
  'scum.BaseBuildingAttackerSentryGrenadeDamageMultiplier': '攻基地机甲榴弹伤害倍率',
  'scum.SentryBaseBuildingDamageMultiplier': '机甲对基地伤害倍率',
  'scum.DropshipDamageMultiplier': '空投飞船伤害倍率',
  'scum.DropshipRailgunDamageMultiplier': '空投飞船轨道炮伤害倍率',
  'scum.DropshipBaseBuildingElementsDamageMultiplier': '空投飞船对基地部件伤害倍率',
  'scum.WeaponDecayDamageOnFiring': '武器开火损耗倍率',
  'scum.EncounterCharacterAggressiveSpawnChanceOverride': '遭遇角色主动刷新概率覆盖值',
  'scum.EncounterCharacterAINoiseResponseRadiusMultiplier': '遭遇角色 AI 噪音响应半径倍率',
  'scum.EncounterHordeNoiseCheckCooldownMultiplier': '遭遇尸潮噪音检查冷却倍率',
  'scum.EncounterHordePuppetHordeActivationScreamOverrideChance': '遭遇尸潮丧尸尸潮激活尖叫覆盖概率',
  'scum.EncounterCanRemoveLowPriorityCharacters': '遭遇允许移除低优先级角色',
  'scum.EncounterCanClampCharacterNumWhenOutOfResources': '资源不足时限制遭遇角色数量',
  'scum.EncounterEnableSpawnPreventionAreaSpawnOnCharacterDeath': '角色死亡时启用防刷区生成',
  'scum.EnableDropshipAbandonedBunkerEncounter': '启用空投飞船废弃地堡遭遇',
  'scum.DropshipAbandonedBunkerEncounterTriggerChance': '空投飞船废弃地堡遭遇触发概率',
  'scum.SpawnEncountersInThreatZonesIgnoringBaseBuilding': '忽略基地建造时在威胁区生成遭遇',
  'scum.BaseBuildingEncounterTimeToFullMinNumToEnd': '基地建造遭遇达到最低结束人数所需时间',
  'scum.BaseBuildingEncounterMaximumMinToEndReduction': '基地建造遭遇最大结束时间缩减',
  'scum.EnableSentryRespawning': '启用机甲重刷',
  'scum.AbandonedBunkerCommotionThreshold': '废弃地堡骚动阈值',
  'scum.AbandonedBunkerCommotionThresholdPerPlayerExtra': '废弃地堡每名玩家额外骚动阈值',
  'scum.AbandonedBunkerEnemyActivationThreshold': '废弃地堡敌人激活阈值',
  'scum.AbandonedBunkerEnemyActivationThresholdPerPlayerExtra': '废弃地堡每名玩家额外敌人激活阈值',
  'scum.AbandonedBunkerResetArmoryLockersOnActivationOnly': '仅在激活时重置废弃地堡军械库储物柜',
  'scum.ProbabilityForArmedNPCToDropItemFromHandsWhenSearched': '搜索时武装非玩家角色手持物品掉落概率',
  'scum.CargoDropZombieEncounterWeightMultiplier': '空投僵尸遭遇权重倍率',
  'scum.CargoDropDropshipEncounterWeightMultiplier': '空投飞船遭遇权重倍率',
  'scum.HuntTriggerChanceOverride_ContinentalForest': '大陆森林狩猎触发概率覆盖值',
  'scum.HuntTriggerChanceOverride_ContinentalMeadow': '大陆草地狩猎触发概率覆盖值',
  'scum.HuntTriggerChanceOverride_Mediterranean': '地中海狩猎触发概率覆盖值',
  'scum.HuntTriggerChanceOverride_Mountain': '山地狩猎触发概率覆盖值',
  'scum.HuntTriggerChanceOverride_Urban': '城市狩猎触发概率覆盖值',
  'scum.HuntTriggerChanceOverride_Village': '村庄狩猎触发概率覆盖值',
  'scum.MaxAllowedKillboxKeycards': '杀戮地堡钥匙卡最大数量',
  'scum.MaxAllowedKillboxKeycards_PoliceStation': '警察局杀戮地堡钥匙卡最大数量',
  'scum.MaxAllowedKillboxKeycards_RadiationZone': '辐射区杀戮地堡钥匙卡最大数量',
  'scum.NPCWorldEncounterSpawnWeightMultiplier': '非玩家角色世界遭遇刷新权重倍率',
  'scum.PuppetCullDistanceOverride': '丧尸裁剪距离覆盖值',
  'scum.EncounterCharacterSpawnDistanceMinOverrideLTZ': '低威胁区遭遇角色最小刷新距离覆盖值',
  'scum.EncounterCharacterSpawnDistanceMaxOverrideLTZ': '低威胁区遭遇角色最大刷新距离覆盖值',
  'scum.EncounterCharacterSpawnDistanceMinOverrideLargePOI': '大型兴趣点遭遇角色最小刷新距离覆盖值',
  'scum.EncounterCharacterSpawnDistanceMaxOverrideLargePOI': '大型兴趣点遭遇角色最大刷新距离覆盖值',
  'scum.EncounterCharacterRespawnDistanceMinOverrideLTZ': '低威胁区遭遇角色最小重刷距离覆盖值',
  'scum.EncounterCharacterRespawnDistanceMaxOverrideLTZ': '低威胁区遭遇角色最大重刷距离覆盖值',
  'scum.EncounterCharacterRespawnDistanceMinOverrideLargePOI': '大型兴趣点遭遇角色最小重刷距离覆盖值',
  'scum.EncounterCharacterRespawnDistanceMaxOverrideLargePOI': '大型兴趣点遭遇角色最大重刷距离覆盖值',
  'scum.EncounterVirtualizedTimeOverride': '遭遇虚拟化时间覆盖值',
  'scum.ArmedNPCNetCullDistanceOverride': '武装非玩家角色网络裁剪距离覆盖值',
  'scum.MinimumDurabilityOfArmedNPCsDroppedItemFromHands': '武装非玩家角色手持掉落物品最低耐久',
  'scum.MaximumDurabilityOfArmedNPCsDroppedItemFromHands': '武装非玩家角色手持掉落物品最高耐久',
  'scum.AnimalNetCullDistanceOverride': '动物网络裁剪距离覆盖值',
  'scum.ArmedNPCLimpingHealthThreshold': '武装非玩家角色瘸行生命阈值',
  'scum.FlagOvertakeDuration': '旗帜占领时长',
  'scum.MaximumAmountOfElementsPerFlag': '每面旗帜最大部件数量',
  'scum.ExtraElementsPerFlagForAdditionalSquadMember': '每增加一名队友可额外拥有的旗帜部件数量',
  'scum.MaximumNumberOfExpandedElementsPerFlag': '每面旗帜最大扩展部件数量',
  'scum.AllowMultipleFlagsPerPlayer': '允许每名玩家拥有多个旗帜',
  'scum.AllowFlagPlacementOnBBElements': '允许在基地建造部件上放置旗帜',
  'scum.ChestAcquisitionDuration': '箱子归属获取时长',
  'scum.WeaponRackMaxAmountPerFlagArea': '每个旗帜区域武器架最大数量',
  'scum.WeaponRackStartDecayingIfFlagAreaHasMoreThan': '旗帜区域武器架超过上限后开始腐坏',
  'scum.WallWeaponRackMaxAmountPerFlagArea': '每个旗帜区域墙挂武器架最大数量',
  'scum.WallWeaponRackStartDecayingIfFlagAreaHasMoreThan': '旗帜区域墙挂武器架超过上限后开始腐坏',
  'scum.WellStartDecayingIfFlagAreaHasMoreThan': '旗帜区域水井超过上限后开始腐坏',
  'scum.TurretStartDecayingIfFlagAreaHasMoreThan': '旗帜区域炮塔超过上限后开始腐坏',
  'scum.AllowFloorPlacementOnHalfAndLowWalls': '允许在半墙和矮墙上放置地板',
  'scum.AllowWallPlacementOnHalfAndLowWalls': '允许在半墙和矮墙上放置墙体',
  'scum.RaidProtectionEnableLog': '启用袭击保护日志',
  'scum.RaidProtectionFlagSpecificChangeSettingCooldown': '旗帜专属袭击保护设置变更冷却',
  'scum.RaidProtectionFlagSpecificChangeSettingPrice': '旗帜专属袭击保护设置变更价格',
  'scum.RaidProtectionFlagSpecificMaxProtectionTime': '旗帜专属袭击保护最大保护时间',
  'scum.RaidProtectionGlobalShouldShowRaidTimesMessage': '全局显示袭击时段消息',
  'scum.WaterProximityReplenishTimeoutMultiplier': '水邻近补给超时倍率',
  'scum.GasolineProximityReplenishTimeoutMultiplier': '汽油邻近补给超时倍率',
  'scum.PropaneProximityReplenishTimeoutMultiplier': '丙烷邻近补给超时倍率',
  'scum.ItemCooldownGroupsDurationMultiplier': '物品冷却组持续时间倍率',
  'scum.SquadMemberCountAtIntLevel1': '智力 1 级小队成员数量',
  'scum.SquadMemberCountAtIntLevel2': '智力 2 级小队成员数量',
  'scum.SquadMemberCountAtIntLevel3': '智力 3 级小队成员数量',
  'scum.SquadMemberCountAtIntLevel4': '智力 4 级小队成员数量',
  'scum.SquadMemberCountAtIntLevel5': '智力 5 级小队成员数量',
  'scum.SquadMemberCountLimitForPunishment': '小队成员处罚数量上限',
  'scum.RTSquadProbationDuration': 'RT 小队观察期时长',
  'scum.SquadMoneyPenaltyPerPrevSquadMember': '每名前队友的小队金钱惩罚',
  'scum.SquadFamePointsPenaltyPerPrevSquadMember': '每名前队友的小队声望点惩罚',
  'scum.ArcherySkillMultiplier': '弓术技能倍率',
  'scum.MeleeWeaponsSkillMultiplier': '近战武器技能倍率',
  'scum.QuestsEnabled': '启用任务',
  'scum.QuestsGlobalCycleDuration': '任务全局周期时长',
  'scum.MaxQuestsPerCyclePerTrader': '每个商人每周期最大任务数',
  'scum.QuestRequirementsBlockTradeableItems': '任务需求禁止可交易物品',
  'scum.TurretsAttackArmedNPCs': '炮塔攻击武装非玩家角色',
  'scum.EnableBCULocking': '启用 BCU 锁定',
  'scum.NameChangeCost': '改名费用',
  'scum.NewPlayerProtectionDuration': '新玩家保护时长',
  'scum.AllowAutomaticParachuteOpening': '允许自动开伞',
  'scum.HideQuickAccessBar': '隐藏快捷栏',
  'scum.EnableDeenaOnServer': '在服务器上启用 Deena 助手',
  'scum.OvenStartDecayingIfFlagAreaHasMoreThan': '旗帜区域烤炉超过上限后开始腐坏',
  'scum.EnableDigitalDeluxeFreeGoldCard': '启用数字豪华版免费金卡',
  'scum.BaseBuildingDestructionLogDamageThreshold': '基地建造摧毁日志伤害阈值',
  'scum.BaseElementsDecayRateMultiplier': '基地部件腐坏速率倍率',
  'scum.SmokerStartDecayingIfFlagAreaHasMoreThan': '旗帜区域熏炉超过上限后开始腐坏',
}

const indexedKinds = {
  MaxAmount: '最大数量',
  MaxFunctionalAmount: '最大可用数量',
  MinPurchasedAmount: '最小购买数量',
}

const indexedVehicleLabels = {
  KingletDuster: '轻型飞机',
  Dirtbike: '越野摩托',
  Laika: '拉伊卡',
  Motorboat: '摩托艇',
  Wheelbarrow: '独轮车',
  Wolfswagen: '沃尔夫斯瓦根',
  Bicycle: '自行车',
  Rager: '皮卡',
  Cruiser: '巡航车',
  Quad: '四轮摩托',
  SmallRaft: '小木筏',
  BigRaft: '大木筏',
  Dinghy: '橡皮艇',
  SUP: '桨板',
  KingletMariner: '水上飞机',
  Tractor: '拖拉机',
  Ris: 'RIS 越野车',
  SidecarBike: '边三轮摩托',
}

const animalLabels = {
  Bear: '熊',
  Boar: '野猪',
  Chicken: '鸡',
  Deer: '鹿',
  Donkey: '驴',
  Goat: '山羊',
  Horse: '马',
  Rabbit: '兔子',
  Wolf: '狼',
}

const localizedTokenLabels = {
  Activation: '激活',
  Active: '活跃',
  Additional: '额外',
  Aggressive: '主动',
  Amount: '数量',
  Animal: '动物',
  Animals: '动物',
  Announcement: '公告',
  Area: '区域',
  Armed: '武装',
  Armory: '军械库',
  Attack: '攻击',
  Attacker: '攻击方',
  Automatic: '自动',
  Aviation: '航空',
  Awareness: '感知',
  Bar: '栏',
  Base: '基础',
  Battery: '电池',
  Batch: '批次',
  BCU: 'BCU',
  BCULocking: 'BCU锁定',
  Bear: '熊',
  Bedroll: '睡袋',
  Big: '大',
  Board: '告示板',
  Body: '身体',
  Boar: '野猪',
  Bonus: '加成',
  Brawling: '拳击',
  Building: '建造',
  Bunker: '地堡',
  Can: '允许',
  Camouflage: '伪装',
  Cap: '上限',
  Card: '卡',
  Cargo: '空投',
  Character: '角色',
  Characters: '角色',
  Chance: '概率',
  Change: '变更',
  Charge: '充电',
  Chest: '箱子',
  Chicken: '鸡',
  Clamp: '限制',
  Climb: '攀爬',
  Commotion: '骚动',
  Commit: '执行',
  Continental: '大陆',
  Cooldown: '冷却',
  Coordinate: '坐标',
  Cooking: '烹饪',
  Count: '数量',
  Cruiser: '巡航车',
  Cull: '裁剪',
  Custom: '自定义',
  Damage: '伤害',
  Day: '日',
  Days: '天',
  Decay: '腐坏',
  Deer: '鹿',
  Defuse: '拆除',
  Deena: 'Deena',
  Delay: '延迟',
  Delete: '删除',
  Deluxe: '豪华',
  Demolition: '爆破',
  Devices: '设备',
  Digital: '数字',
  Difficulty: '难度',
  Dinghy: '橡皮艇',
  Disable: '禁用',
  Distance: '距离',
  Donkey: '驴',
  Door: '门',
  Doors: '门',
  Dropship: '空投飞船',
  Drone: '无人机',
  Drones: '无人机',
  Drain: '消耗',
  Driving: '驾驶',
  Duster: 'Duster',
  Dynamo: '发电轮',
  Elements: '部件',
  Enable: '启用',
  End: '结束',
  Endurance: '耐力',
  Enemy: '敌人',
  Encounter: '遭遇',
  Engineering: '工程',
  Entities: '实体',
  Event: '事件',
  Events: '事件',
  Examine: '检查',
  Exhaustion: '力竭',
  Expanded: '扩展',
  Expiration: '过期',
  Exterior: '户外',
  Extra: '额外',
  Failure: '失败',
  Fall: '下落',
  Fame: '声望',
  Farming: '农业',
  First: '首次',
  Fishing: '钓鱼',
  Flag: '旗帜',
  Floor: '地板',
  Fog: '雾',
  Food: '食物',
  Forbidden: '禁区',
  Functional: '可用',
  Gain: '获取',
  Garage: '车库',
  Garden: '花园',
  Gasoline: '汽油',
  Ghost: '残影',
  Global: '全局',
  Goat: '山羊',
  Gold: '黄金',
  Grenade: '榴弹',
  Ground: '地面',
  Group: '组',
  Groups: '组',
  Handgun: '手枪',
  Half: '半高',
  Hands: '手持',
  Harvest: '收获',
  Health: '生命',
  Height: '高度',
  High: '高',
  Hide: '隐藏',
  Horde: '尸潮',
  Horse: '马',
  Hours: '小时',
  Human: '玩家',
  Hunt: '狩猎',
  HTZ: '高威胁区',
  Indicators: '指示器',
  Inactive: '不活跃',
  Inactivity: '闲置',
  Increase: '增加',
  Initial: '初始',
  Inertia: '惯性',
  Ignoring: '忽略',
  Inner: '内部',
  Interior: '室内',
  Interest: '参与率',
  Interval: '间隔',
  Int: '智力',
  Item: '物品',
  Items: '物品',
  Jump: '跳跃',
  Key: '钥匙',
  Keycards: '钥匙卡',
  Killbox: '杀戮地堡',
  Laika: '拉伊卡',
  Last: '最后',
  Level: '等级',
  Life: '生命',
  Limping: '瘸行',
  Local: '本地',
  Lockability: '可上锁',
  Locked: '上锁',
  Lockers: '储物柜',
  Logging: '日志',
  Logs: '日志',
  Loot: '战利品',
  Low: '低',
  LTZ: '低威胁区',
  Maintan: '维护',
  Maintain: '维护',
  Manager: '管理器',
  Map: '地图',
  Mariner: 'Mariner',
  Max: '最大',
  Maximum: '最大',
  Meadow: '草地',
  Medical: '医疗',
  Mediterranean: '地中海',
  Melee: '近战',
  Member: '成员',
  Message: '消息',
  Messages: '消息',
  Min: '最小',
  Minimal: '最小',
  Mines: '地雷',
  Minimum: '最小',
  Mode: '模式',
  Money: '金钱',
  Motorcycle: '摩托车',
  Mountain: '山地',
  Movement: '移动',
  Multiplier: '倍率',
  MTZ: '中威胁区',
  Name: '名称',
  Net: '网络',
  Network: '网络',
  Never: '永不',
  New: '新',
  Nighttime: '夜间',
  Noise: '噪音',
  Notice: '公告',
  Num: '数量',
  Number: '数量',
  NPC: 'NPC',
  NPCs: 'NPC',
  Object: '对象',
  Objects: '对象',
  Offline: '离线',
  On: '',
  Only: '仅',
  Open: '打开',
  Opening: '开启',
  Out: '',
  Oven: '烤炉',
  Outside: '外部',
  Pack: '包',
  Partial: '部分',
  Penalty: '惩罚',
  Per: '每',
  Percentage: '百分比',
  Periodic: '周期',
  Phone: '电话',
  Placement: '放置',
  Plant: '植物',
  Play: '播放',
  Player: '玩家',
  Players: '玩家',
  Point: '点数',
  Points: '点数',
  POI: '兴趣点',
  Positive: '正向',
  Prev: '前',
  Price: '价格',
  Prisoners: '囚犯',
  Probability: '概率',
  Proximity: '邻近',
  Promotion: '提升',
  Protection: '保护',
  Propane: '丙烷',
  Probation: '观察期',
  Puppet: '丧尸',
  Puppets: '丧尸',
  Purchased: '购买',
  Quest: '任务',
  Quests: '任务',
  Quick: '快捷',
  Rabbit: '兔子',
  Rack: '架',
  Radius: '半径',
  Raid: '袭击',
  Railgun: '轨道炮',
  Random: '随机',
  Rager: '皮卡',
  Raft: '木筏',
  Refill: '补充',
  Relevancy: '相关性',
  Remove: '移除',
  Replenish: '补给',
  Requirements: '需求',
  Reset: '重置',
  Resources: '资源',
  Respawning: '重刷',
  Respawn: '重生',
  Reward: '奖励',
  Rifle: '步枪',
  Rifles: '步枪',
  Ris: 'RIS',
  Rotation: '轮换',
  RT: 'RT',
  Running: '跑步',
  Safe: '安全',
  Screen: '界面',
  Scream: '尖叫',
  Searched: '搜索',
  Secret: '秘密',
  Sector: '区域',
  Selected: '选定',
  Send: '发送',
  ServerSide: '服务端',
  Sentries: '机甲',
  Sentry: '机甲',
  Server: '服务器',
  Settings: '设置',
  Shelter: '庇护所',
  Show: '显示',
  Should: '应',
  Sidecar: '边车',
  Simultaneous: '同时',
  Simultaneously: '同时',
  Simulation: '模拟',
  Size: '规模',
  Skill: '技能',
  Skills: '技能',
  Small: '小',
  Smoker: '熏炉',
  Sniping: '狙击',
  Sound: '音效',
  Spawn: '生成',
  Spawner: '刷新器',
  Spawning: '刷新',
  Speed: '速度',
  Spread: '散布',
  Squad: '小队',
  Squadmate: '队友',
  Stamina: '耐力',
  Start: '开始',
  Starter: '初始',
  Stealth: '潜行',
  Suicide: '自杀',
  Sun: '太阳',
  Sunrise: '日出',
  Sunset: '日落',
  SUP: '桨板',
  Survival: '生存',
  SearchedItem: '搜索物品',
  Threshold: '阈值',
  Thievery: '偷窃',
  Threat: '威胁',
  Throwing: '投掷',
  Time: '时间',
  Timed: '限时',
  Timer: '计时器',
  Timeout: '超时',
  To: '',
  Tradeable: '可交易',
  Trader: '商人',
  Traps: '陷阱',
  Tractor: '拖拉机',
  Trigger: '触发',
  Turret: '炮塔',
  Turrets: '炮塔',
  Type: '类型',
  Unit: '单位',
  Unarmed: '徒手',
  Urban: '城市',
  User: '用户',
  Users: '用户',
  VAC: 'VAC',
  Vault: '翻越',
  Vehicle: '载具',
  Vehicles: '载具',
  Version: '版本',
  Virtualized: '虚拟化',
  Virtualization: '虚拟化',
  Visibility: '可见性',
  Visitor: '访客',
  Visitors: '访客',
  Voting: '投票',
  Wall: '墙',
  Walls: '墙',
  Watchdog: '看门狗',
  Water: '水',
  Weight: '权重',
  Well: '水井',
  Wheelbarrow: '独轮车',
  Width: '宽度',
  Wild: '野外',
  Windows: '窗户',
  Widget: '组件',
  Wolf: '狼',
  Wolfswagen: '沃尔夫斯瓦根',
  World: '世界',
  Zone: '区域',
  Zombie: '僵尸',
  Zombies: '僵尸',
}

const localizeByTokens = (key) => {
  const normalizedKey = String(key || '').trim().replace(/^scum\./i, '')
  if (!normalizedKey) {
    return ''
  }
  const tokens = normalizedKey
    .replace(/\./g, ' ')
    .replace(/([a-z0-9])([A-Z])/g, '$1 $2')
    .replace(/([A-Z]+)([A-Z][a-z0-9]+)/g, '$1 $2')
    .replace(/[_-]+/g, ' ')
    .split(/\s+/)
    .filter(Boolean)
  let translatedCount = 0
  const translated = tokens.map((token) => {
    if (localizedTokenLabels[token] !== undefined) {
      if (localizedTokenLabels[token]) {
        translatedCount += 1
      }
      return localizedTokenLabels[token]
    }
    return token
  }).filter(Boolean)
  if (translatedCount === 0 || translatedCount * 2 < tokens.length) {
    return ''
  }
  return translated.join('')
}

const localizedPatternRules = [
  {
    pattern: /^scum\.(KingletDuster|Dirtbike|Laika|Motorboat|Wheelbarrow|Wolfswagen|Bicycle|Rager|Cruiser|Quad|SmallRaft|BigRaft|Dinghy|SUP|KingletMariner|Tractor|Ris|SidecarBike)(MaxAmount|MaxFunctionalAmount|MinPurchasedAmount)$/i,
    render: ([, vehicle, kind]) => `${indexedVehicleLabels[vehicle] || vehicle}${indexedKinds[kind] || kind}`,
  },
  {
    pattern: /^scum\.(Bear|Boar|Chicken|Deer|Donkey|Goat|Horse|Rabbit|Wolf)MaxHealthMultiplier$/i,
    render: ([, animal]) => `${animalLabels[animal] || animal}生命倍率`,
  },
]

// localizeSettingKey returns a curated Chinese label for known SCUM settings.
// key is the canonical scum.* config key, and the function returns a localized label or an empty string when no curated translation exists.
export const localizeSettingKey = (key) => {
  const normalizedKey = String(key || '').trim()
  if (!normalizedKey) {
    return ''
  }
  if (explicitSettingLabels[normalizedKey]) {
    return explicitSettingLabels[normalizedKey]
  }
  for (const rule of localizedPatternRules) {
    const matched = normalizedKey.match(rule.pattern)
    if (matched) {
      return rule.render(matched)
    }
  }
  return localizeByTokens(normalizedKey)
}
